services:
  dockdroid:
    build: .
    volumes:
      #RW
      # ROM source
      - ~/docker_droid/src:/droid_workdir/src
      # Log files
      - ~/docker_droid/logs:/droid_workdir/logs
      # CCache to speed up builds
      - ~/docker_droid/ccache:/mnt/ccache
      # Keys for signing
      - ~/docker_droid/keys:/droid_workdir/keys # aosp does weird chmod stuff in here
      #RO
      # Gitconfig for repo
      - ~/docker_droid/dotfiles/.gitconfig:/droid_workdir/.gitconfig:ro
      # SSH keys for git authentification
      - ~/docker_droid/dotfiles/.ssh:/droid_workdir/.ssh:ro
    env_file:
      - path: ./target.env
        required: false
      - path: ./config.env
        required: false
